name: Docs Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install sphinx
          # Add other dependencies from docs/requirements.txt if needed
      - name: Build docs
        run: make -C docs html # Assuming default target builds HTML
